---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  vars:
    hostname: "192.168.1.1"
    hpe1820__password: ""
    hpe1820__username: "admin"
  tasks:
    - name: Ensure port 2 has two VLANs assigned and 3 none
      hp-procurve:
        port_vlans:
          "7":
            untagged: 2900
            tagged:
              - 295
          "3":
            untagged: null
            tagged: []
        host: "{{ hostname }}"
        username: "{{ hpe1820__username | d(omit) }}"
        password: "{{ hpe1820__password }}"
      delegate_to: "localhost"
    - name: Set Spanning Tree Protocol
      hp-procurve-spanning-tree:
        mode: ieee_802_1d
        enabled: true
        priority: 16384
        username: "{{ hpe1820__username | d(omit) }}"
        password: "{{ hpe1820__password }}"
        host: "{{ hostname }}"
